### ISSUE TITLE
@PreAuthorize and other security's annotations doesn't work on MainController if I will deploy it in WebLogic

### ISSUE THREAD

**Issue by captim** [captim/Gradebook#2]
Если добавить аннотацию @PreAuthorize() над каким либо методом контроллера, вылетает следующий exception:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainController' defined in file [D:\stuff\Homework\Java\GradebookLab3\target\GradebookLab3\WEB-INF\classes\com\dumanskiy\timur\gradebook\controller\MainController.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
(и большой стек трейс)
Последнее Couse by: java.lang.VerifyError: Stack map does not match the one at exception handler 9
Exception Details:
  Location:
    com/dumanskiy/timur/gradebook/controller/MainController$$EnhancerBySpringCGLIB$$b0f7d76e.<init>()V @9: athrow
  Reason:
    Current frame's flags are not assignable to stack map frame's.
  Current Frame:
    bci: @0
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'java/lang/RuntimeException' }
  Stackmap Frame:
    bci: @9
    flags: { }
    locals: { }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2a59 b701 50b8 0038 b1bf bb00 4e5a 5fb7
    0x0000010: 0051 bf                                
  Exception Handler Table:
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 10
  Stackmap Table:
    full_frame(@9,{},{Object[#76]})
    same_locals_1_stack_item_frame(@10,Object[#76])

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
	Truncated. see log file for complete stacktrace
> 
<20.04.2020 20:00:36,830 EEST> <Error> <Deployer> <BEA-149231> <Unable to set the activation state to true for the application "GradebookLab3_war_exploded".
weblogic.application.ModuleException: java.lang.VerifyError: Stack map does not match the one at exception handler 9
Exception Details:
  Location:
    com/dumanskiy/timur/gradebook/controller/MainController$$EnhancerBySpringCGLIB$$b0f7d76e.<init>()V @9: athrow
  Reason:
    Current frame's flags are not assignable to stack map frame's.
  Current Frame:
    bci: @0
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'java/lang/RuntimeException' }
  Stackmap Frame:
    bci: @9
    flags: { }
    locals: { }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2a59 b701 50b8 0038 b1bf bb00 4e5a 5fb7
    0x0000010: 0051 bf                                
  Exception Handler Table:
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 10
  Stackmap Table:
    full_frame(@9,{},{Object[#76]})
    same_locals_1_stack_item_frame(@10,Object[#76])

	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.VerifyError: Stack map does not match the one at exception handler 9
Exception Details:
  Location:
    com/dumanskiy/timur/gradebook/controller/MainController$$EnhancerBySpringCGLIB$$b0f7d76e.<init>()V @9: athrow
  Reason:
    Current frame's flags are not assignable to stack map frame's.
  Current Frame:
    bci: @0
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'java/lang/RuntimeException' }
  Stackmap Frame:
    bci: @9
    flags: { }
    locals: { }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2a59 b701 50b8 0038 b1bf bb00 4e5a 5fb7
    0x0000010: 0051 bf                                
  Exception Handler Table:
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 9
    bci [0, 9] => handler: 10
  Stackmap Table:
    full_frame(@9,{},{Object[#76]})
    same_locals_1_stack_item_frame(@10,Object[#76])

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:571)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
	Truncated. see log file for complete stacktrace

**Comment by captim** [comment]
Проблема с созданием бина "mainController" решена: 1bf9d2f
Не подключил какую то дополнительную зависимость.
Но теперь другой exception при переходе на маппинг с аннотацией @PreAuthorized: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext

**Comment by captim** [comment]
Commit number: 480e4c6
